# -----------------------------
# Server Settings
# -----------------------------
[server]
fileWatcherType = "poll"
enableStaticServing = true

# -----------------------------
# Client Settings
# -----------------------------
[client]
toolbarMode = "minimal"

# -----------------------------
# Theme Settings (current Streamlit 1.30+)
# -----------------------------
[theme]
base = "dark"                            # base theme: "light" or "dark"
primaryColor = "#00BFFF"                 # buttons, highlights
backgroundColor = "#1C1E22"             # main app background
secondaryBackgroundColor = "#2C2F33"    # panels, cards
textColor = "#F0F0F0"                    # main text
font = "sans serif"                      # allowed: "sans serif", "serif", "monospace"

# -----------------------------
# Optional: Custom Fonts via CSS
# -----------------------------
[[theme.fontFaces]]
family = "Roboto"
url = "https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"

[[theme.fontFaces]]
family = "Roboto Slab"
url = "https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@400;700&display=swap"

[[theme.fontFaces]]
family = "Source Code Pro"
url = "https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;700&display=swap"

# -----------------------------
# Chart / Plot Defaults
# -----------------------------
[theme.chart]
backgroundColor = "#2C2F33"        # Chart panel background
gridColor = "#3A3F45"              # Grid lines
axisColor = "#F0F0F0"              # Axis text & labels
lineColor = "#00BFFF"              # Default line plot color
hoverLineColor = "#1E90FF"         # Line when hovering
signalBuyColor = "#32CD32"         # Buy signal
signalSellColor = "#FF4500"        # Sell signal
highlightColor = "#FFD700"         # Highlight lines/markers
volumeColor = "#FF8C00"            # Volume bars / alerts
tooltipBackground = "#262A2F"      # Hover tooltip bg
tooltipTextColor = "#F0F0F0"       # Hover tooltip text

# -----------------------------
# Additional UI / Dashboard Styling
# -----------------------------
[theme.dashboard]
componentBackground1 = "#262A2F"  # Cards, small panels
componentBackground2 = "#3A3F45"  # Secondary panels
textMuted = "#A0A0A0"             # Secondary / label text

# -----------------------------
# Optional: Sizes & Weights (apply via CSS in Python)
# -----------------------------
# headingFontSizes = ["32px", "28px", "24px", "20px", "18px", "16px"]
# headingFontWeights = ["700", "600", "500", "400", "400", "300"]
# codeFontSize = "14px"
# codeFontWeight = "400"

# -----------------------------
# Sidebar Font (Optional, apply via CSS in Python)
# -----------------------------
# [theme.sidebar]
# font = "sans serif, serif, monospace"
# headingFont = "sans serif, serif, monospace"
# codeFont = "Source Code Pro, monospace"